### ISSUE TITLE
Response to publisher/identity should be normalized

### ISSUE THREAD

**Issue by mikel2000** [brave-intl/bat-publisher#28]
Requests to identity which return the same publisher should also return the same properties.

`https://ledger.mercury.basicattentiontoken.org/v3/publisher/identity?publisher=washingtonpost.com` returns `publisher: "washingtonpost.com"` and the property `verified: true`.

`https://ledger.mercury.basicattentiontoken.org/v3/publisher/identity?publisher=www.washingtonpost.com` returns also `publisher: "washingtonpost.com"` but the property `verified` is missing.

**Comment by mrose17** [comment]
Fixed by https://github.com/brave-intl/bat-ledger/pull/188
